---
- hosts: all
  serial: 100%
  vars:
    epel: true
    no_selinux: true
    no_firewalld: true
  roles:
    - base

- hosts: etcd
  roles:
    - etcd

- hosts: all
  roles:
    - flannel

- hosts: kubemaster
  roles:
    - kubernetes-master

- hosts: kubeminions
  roles:
    - kubernetes-minion